### ISSUE TITLE
Use with patternlab-php/twig

### ISSUE THREAD

**Issue by froboy** [pattern-lab/plugin-node-tab#16]
Greetings,
I'm trying to use this plugin with the PHP/Twig flavor of PatternLab. I've used npm to get the plugin, added this to my config.yml: 
```plugins:
  plugin-node-tab:
    enabled: true
    initialized: false
```

but I'm not able to get the plugin working. So 1) is this even possible? 2) any idea how?

My setup:
- pattern-lab/core v2.7.0
- pattern-lab/patternengine-twig v2.1.2
- pattern-lab/styleguidekit-twig-default v3.0.0

**Comment by bmuenzenmeyer** [comment]
I am a bit confused by the issue report. Are you using Pattern Lab PHP or Pattern Lab Node?

**Comment by froboy** [comment]
I'm using Pattern Lab PHP, but I didn't see any equivalent project for the PHP version of the plugin so I thought I'd try here. I'm happy to redirect the question elsewhere if there's a better place for it.

**Comment by bmuenzenmeyer** [comment]
ok. Unfortunately this plugin and its behavior are only supported within Pattern Lab Node at this time. A better place to redirect this would be the the PHP side of the organization, like https://github.com/pattern-lab/patternlab-php

**Comment by froboy** [comment]
No worries. Thanks!
