### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by arolonger** [pattern-lab/plugin-node-tab#9]
Hey,

I've just installed your plugin on edition-node-gulp.
Message below:

> ? Specify filetype(s) to create a tab for. Separate multiple filetypes with a space, pipe or comma. Example: js css >>>
>   css js
> Adding configuration for tabs [ 'css', 'js' ] inside package.json
> 
> edition-node-gulp@1.3.2 postinstall D:\PatternLab
> node scripts/postinstall.js
> 
> Beginning Pattern Lab Node Gulp postinstall...
> Beginning Pattern Lab postinstall...
> No starterkits found to automatically load.
> Pattern Lab postinstall complete.

and it doesn't work.
No entry added to patternlab-config.json, nothing change.
Could you give me some advices what I did wrong?

**Comment by ioss** [comment]
This worked for me: 
Try to change "patternlab-node" dependency to "^2.6.0-alpha" in your edition-node-gulp/package.json (and let "npm i" get the new version). Plugins are only available in the dev-branch. (at least I only checked there).

And don't forget to enable the plugin by adding it to the patternlab-config.json (see the other issue here)

**Comment by arolonger** [comment]
I can confirm. Upgrade to 2.6.0-alpha did the job (y).
Thank you for your help
